---
- hosts: all
  become: true
  tasks:
  - name: Create EC2 instances
    amazon.aws.ec2_instance:
      name: "clement-ansible"
      key_name: "ubuntu"
      instance_type: t2.micro
      security_group: My-security-group
      region: us-east-1
      aws_access_key: "AKIAWCZC5ZCVWFTGYAOM"  
      aws_secret_key: "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"        
      network:
        assign_public_ip: true
      image_id: "ami-053a45fff0a704a47"
